/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityItem: typeof import('./src/components/ActivityItem/index.vue')['default']
    AndPrivacy: typeof import('./src/components/andPrivacy/index.vue')['default']
    AvatarGroup: typeof import('./src/components/AvatarGroup/index.vue')['default']
    CitySelector: typeof import('./src/components/CitySelector/CitySelector.vue')['default']
    CustomDivder: typeof import('./src/components/customDivder/index.vue')['default']
    CustomEmpty: typeof import('./src/components/customEmpty/index.vue')['default']
    CustomLoading: typeof import('./src/components/CustomLoading/index.vue')['default']
    CustomTabBar: typeof import('./src/components/CustomTabBar/index.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState/index.vue')['default']
    Example: typeof import('./src/components/AvatarGroup/example.vue')['default']
    GuardianRegisterForm: typeof import('./src/components/GuardianRegisterForm/index.vue')['default']
    H5TabBar: typeof import('./src/components/H5TabBar/index.vue')['default']
    ImageCaptcha: typeof import('./src/components/ImageCaptcha/index.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload/index.vue')['default']
    PageLoading: typeof import('./src/components/PageLoading/index.vue')['default']
    RegionSelector: typeof import('./src/components/RegionSelector/RegionSelector.vue')['default']
    SignupSelector: typeof import('./src/components/SignupSelector/index.vue')['default']
    SimpleRegionSelector: typeof import('./src/components/SimpleRegionSelector/SimpleRegionSelector.vue')['default']
    StatusBar: typeof import('./src/components/statusBar/index.vue')['default']
    StatusStamp: typeof import('./src/components/StatusStamp/index.vue')['default']
    StudyPlanItem: typeof import('./src/components/StudyPlanItem/index.vue')['default']
    VolunteerRegisterForm: typeof import('./src/components/VolunteerRegisterForm/index.vue')['default']
  }
}
